# Supabase CLI project configuration
# https://supabase.com/docs/guides/local-development

[project]
id = "igarden-demo"

[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
